config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :scores
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/score.rb
class Score < ApplicationRecord
    validates :name, :score_a, :score_b, :score_c, presence: true
    before_save :sort_the_value!

    private
        def sort_the_value!
            temp_array = [self.score_a, self.score_b, self.score_c]
            temp_array = temp_array.sort().reverse()

            result = []
            
            temp_array.each do |element|
                if element == self.score_a
                    result.append("A")
                elsif element == self.score_b
                    result.append("B")
                else
                    result.append("C")
                end
            end

            self.sorting = result.join(", ").to_s
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
    def index
        @scores = Score.order 'updated_at DESC'
    end

    def show
        @score = Score.find params[:id]
    end

    def new
        @score = Score.new
    end

    def create
        @score = Score.new score_params

        if @score.save
            redirect_to score_path(@score.id)
        else
            render :new
        end
    end

    private
        def score_params
            params.require(:score).permit(:name, :score_a, :score_b, :score_c)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/index.html.haml
%h3 INDEX

%table{border:1 }
    %thead 
        %tr 
            %td{colspan: 5} Sorting
        %tr 
            %td Nama
            %td A
            %td B
            %td C
            %td Urutan
    %tbody 
        - @scores.each do |score|
            %tr 
                %td= link_to score.name, score_path(score)
                %td= score.score_a
                %td= score.score_b
                %td= score.score_c
                %td= score.sorting
 
= link_to 'Tambah', new_score_path

app/views/scores/new.html.haml
= form_for @score do |f|
    %p 
        = f.label :name, "Nama"
        = f.text_field :name
    %p 
        = f.label :score_a, "A"
        = f.text_field :score_a
    %p 
        = f.label :score_b, "B"
        = f.text_field :score_b
    %p 
        = f.label :score_c, "C"
        = f.text_field :score_c
    %p
        = f.submit "Hitung"

app/views/scores/show.html.haml
%h3 SHOW

%table 
    %tbody
        %tr 
            %td Nama
            %td= @score.name
        %tr 
            %td A
            %td= @score.score_a
        %tr 
            %td B
            %td= @score.score_b
        %tr 
            %td C
            %td= @score.score_c
        %tr 
            %td Urutan
            %td= @score.sorting

= link_to "Kembali", scores_path